extends Node
## Autoload "Audio": buses, pooled SFX voices, cross-faded music and ambience.
## All streams are generated by tools/generate_audio.py (original audio).

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"
const BUSES := ["Music", "SFX", "Ambience", "Voice", "UI"]
const VOICE_SFX := ["grunt", "battle_cry", "death_cry", "victory_cry"]

## name -> number of variants on disk.
const SFX_VARIANTS := {
	"clash": 3, "clash_shield": 2, "whoosh": 3, "impact_flesh": 2, "slam": 2, "step": 3, "hoof": 2,
	"land": 1, "armor_fall": 2, "magic_charge": 1, "magic_cast": 2, "magic_impact": 2, "thunder": 2,
	"dash": 1, "power_up": 1, "finisher_impact": 1, "slash_hit": 2, "blade_grind": 1, "heartbeat": 1,
	"wind": 1, "draw_weapon": 1, "jump": 1, "grunt": 3, "battle_cry": 2, "death_cry": 2, "victory_cry": 1,
	"horse_neigh": 1, "piece_place": 2, "check": 1, "checkmate": 1, "promotion": 1, "game_start": 1,
	"capture_quick": 2, "ui_hover": 1, "ui_click": 1, "ui_back": 1, "ui_open": 1, "ui_error": 1,
}
const MUSIC_LOOPS := {"menu": true, "board": true, "battle": true, "climax": true, "victory": false, "defeat": false}
const POOL_SIZE := 20

var _streams: Dictionary = {}
var _pool: Array[AudioStreamPlayer] = []
var _pool_index: int = 0
var _music_players: Array[AudioStreamPlayer] = []
var _active_music: int = 0
var _current_music: String = ""
var _ambience: AudioStreamPlayer
var _music_tween: Tween


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_setup_buses()
	for name: String in SFX_VARIANTS:
		var list: Array[AudioStream] = []
		for v in SFX_VARIANTS[name]:
			var path := SFX_DIR + "%s_%d.ogg" % [name, v]
			if ResourceLoader.exists(path):
				list.append(load(path))
		_streams[name] = list
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_pool.append(p)
	for i in 2:
		var m := AudioStreamPlayer.new()
		m.bus = "Music"
		m.volume_db = -80.0
		add_child(m)
		_music_players.append(m)
		m.finished.connect(_on_music_finished.bind(m))
	_ambience = AudioStreamPlayer.new()
	_ambience.bus = "Ambience"
	add_child(_ambience)
	apply_volumes()
	Settings.changed.connect(func(section: String, _key: String) -> void:
		if section == "audio":
			apply_volumes())


func _setup_buses() -> void:
	for bus_name: String in BUSES:
		if AudioServer.get_bus_index(bus_name) == -1:
			AudioServer.add_bus()
			var idx := AudioServer.bus_count - 1
			AudioServer.set_bus_name(idx, bus_name)
			AudioServer.set_bus_send(idx, "Master")
	# A touch of hall reverb glues synthesized effects into the space.
	var sfx := AudioServer.get_bus_index("SFX")
	if AudioServer.get_bus_effect_count(sfx) == 0:
		var reverb := AudioEffectReverb.new()
		reverb.room_size = 0.55
		reverb.damping = 0.6
		reverb.wet = 0.12
		reverb.dry = 1.0
		AudioServer.add_bus_effect(sfx, reverb)
		var limiter := AudioEffectHardLimiter.new()
		AudioServer.add_bus_effect(sfx, limiter)


func apply_volumes() -> void:
	_set_bus("Master", Settings.get_value("audio", "master"))
	for key: String in ["music", "sfx", "ambience", "voice", "ui"]:
		var bus_name: String = {"music": "Music", "sfx": "SFX", "ambience": "Ambience", "voice": "Voice", "ui": "UI"}[key]
		_set_bus(bus_name, Settings.get_value("audio", key))


func _set_bus(bus_name: String, linear: Variant) -> void:
	var idx := AudioServer.get_bus_index(bus_name)
	if idx < 0:
		return
	var v := clampf(float(linear), 0.0, 1.0)
	AudioServer.set_bus_volume_db(idx, linear_to_db(maxf(v, 0.0001)))
	AudioServer.set_bus_mute(idx, v <= 0.001)


func play_sfx(sfx_name: String, volume_db: float = 0.0, pitch: float = 1.0) -> void:
	var list: Array = _streams.get(sfx_name, [])
	if list.is_empty():
		return
	var p := _pool[_pool_index]
	_pool_index = (_pool_index + 1) % _pool.size()
	p.stream = list[randi() % list.size()]
	p.volume_db = volume_db
	p.pitch_scale = clampf(pitch, 0.25, 4.0)
	if sfx_name.begins_with("ui_"):
		p.bus = "UI"
	elif sfx_name in VOICE_SFX:
		p.bus = "Voice"
	else:
		p.bus = "SFX"
	p.play()


func ui(kind: String) -> void:
	play_sfx("ui_" + kind, -4.0 if kind == "hover" else 0.0, randf_range(0.97, 1.03))


## Cross-fades to a music cue ("menu", "board", "battle", "climax", "victory",
## "defeat"). Re-requesting the current cue does nothing.
func music(cue: String, fade_time: float = 1.2) -> void:
	if cue == _current_music:
		return
	var path := MUSIC_DIR + cue + ".ogg"
	if not ResourceLoader.exists(path):
		return
	_current_music = cue
	var stream: AudioStream = load(path)
	if stream is AudioStreamOggVorbis:
		(stream as AudioStreamOggVorbis).loop = MUSIC_LOOPS.get(cue, true)
	var old := _music_players[_active_music]
	_active_music = 1 - _active_music
	var new := _music_players[_active_music]
	new.stream = stream
	new.volume_db = -40.0
	new.play()
	if _music_tween:
		_music_tween.kill()
	_music_tween = create_tween().set_parallel(true)
	_music_tween.tween_property(new, "volume_db", 0.0, fade_time).set_trans(Tween.TRANS_SINE)
	_music_tween.tween_property(old, "volume_db", -60.0, fade_time).set_trans(Tween.TRANS_SINE)
	_music_tween.chain().tween_callback(old.stop)


func current_music() -> String:
	return _current_music


func _on_music_finished(player: AudioStreamPlayer) -> void:
	# One-shot stings return to the board theme.
	if player == _music_players[_active_music] and not MUSIC_LOOPS.get(_current_music, true):
		music("board", 2.0)


func ambience(enabled: bool) -> void:
	if enabled:
		if not _ambience.playing:
			var stream: AudioStream = load("res://assets/audio/ambience/hall.ogg")
			if stream is AudioStreamOggVorbis:
				(stream as AudioStreamOggVorbis).loop = true
			_ambience.stream = stream
			_ambience.play()
	else:
		_ambience.stop()


func _exit_tree() -> void:
	# Stop every voice so no stream playback outlives the engine.
	for p in _pool:
		p.stop()
		p.stream = null
	for m in _music_players:
		m.stop()
		m.stream = null
	_ambience.stop()
	_ambience.stream = null
	_streams.clear()
